# Welcome to the First Scratchbook
---

Here my goal will be to acquire and prepare the data!

End goal: predict sales of video games

In [1]:
#imports
import pandas as pd
import numpy as np

In [2]:
#bring in our csv
df = pd.read_csv('data/vgsales12-4-2019.csv')

In [3]:
#check the shape
df.shape

(55792, 16)

In [4]:
#how does it look?
df.head()

,Rank,Name,Genre,ESRB_Rating,Platform,Publisher,Developer,Critic_Score,User_Score,Total_Shipped,Global_Sales,NA_Sales,PAL_Sales,JP_Sales,Other_Sales,Year
0,1,Wii Sports,Sports,E,Wii,Nintendo,Nintendo EAD,7.7,NaN,82.86,NaN,NaN,NaN,NaN,NaN,2006.0
1,2,Super Mario Bros.,Platform,NaN,NES,Nintendo,Nintendo EAD,10.0,NaN,40.24,NaN,NaN,NaN,NaN,NaN,1985.0
2,3,Mario Kart Wii,Racing,E,Wii,Nintendo,Nintendo EAD,8.2,9.1,37.14,NaN,NaN,NaN,NaN,NaN,2008.0
3,4,PlayerUnknown's Battlegrounds,Shooter,NaN,PC,PUBG Corporation,PUBG Corporation,NaN,NaN,36.60,NaN,NaN,NaN,NaN,NaN,2017.0
4,5,Wii Sports Resort,Sports,E,Wii,Nintendo,Nintendo EAD,8.0,8.8,33.09,NaN,NaN,NaN,NaN,NaN,2009.0

In [5]:
#I'm going to lowercase all of the columns
df.columns= df.columns.str.strip().str.lower()
df.columns

Index(['rank', 'name', 'genre', 'esrb_rating', 'platform', 'publisher',
       'developer', 'critic_score', 'user_score', 'total_shipped',
       'global_sales', 'na_sales', 'pal_sales', 'jp_sales', 'other_sales',
       'year'],
      dtype='object')

In [6]:
#already noticing a lot of null values. 
df.isna().sum()

rank                 0
name                 0
genre                0
esrb_rating      32169
platform             0
publisher            0
developer           17
critic_score     49256
user_score       55457
total_shipped    53965
global_sales     36377
na_sales         42828
pal_sales        42603
jp_sales         48749
other_sales      40270
year               979
dtype: int64

In [7]:
#fill nulls in global_sales with 0
df['global_sales'] = df['global_sales'].fillna(0)

In [8]:
#fill nulls in total_shipped with 0
df['total_shipped'] = df['total_shipped'].fillna(0)

In [9]:
#quality assurance
df

,rank,name,genre,esrb_rating,platform,publisher,developer,critic_score,user_score,total_shipped,global_sales,na_sales,pal_sales,jp_sales,other_sales,year
0,1,Wii Sports,Sports,E,Wii,Nintendo,Nintendo EAD,7.7,NaN,82.86,0.0,NaN,NaN,NaN,NaN,2006.0
1,2,Super Mario Bros.,Platform,NaN,NES,Nintendo,Nintendo EAD,10.0,NaN,40.24,0.0,NaN,NaN,NaN,NaN,1985.0
2,3,Mario Kart Wii,Racing,E,Wii,Nintendo,Nintendo EAD,8.2,9.1,37.14,0.0,NaN,NaN,NaN,NaN,2008.0
3,4,PlayerUnknown's Battlegrounds,Shooter,NaN,PC,PUBG Corporation,PUBG Corporation,NaN,NaN,36.60,0.0,NaN,NaN,NaN,NaN,2017.0
4,5,Wii Sports Resort,Sports,E,Wii,Nintendo,Nintendo EAD,8.0,8.8,33.09,0.0,NaN,NaN,NaN,NaN,2009.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55787,55788,Indivisible,Role-Playing,NaN,PC,505 Games,Lab Zero Games,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,2019.0
55788,55789,Lost Ember,Adventure,RP,PC,Mooneye Studios,Mooneye Studios,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,2019.0
55789,55790,Lost Ember,Adventure,RP,PS4,Mooneye Studios,Mooneye Studios,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,2019.0
55790,55791,Lost Ember,Adventure,RP,XOne,Mooneye Studios,Mooneye Studios,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,2019.0
55791,55792,Falcon Age,Action-Adventure,NaN,PS4,Unknown,Outerloop Games,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN

In [10]:
#create a total_sales column which is total_shipped plus global_sales
df['total_sales'] = df['total_shipped'] + df['global_sales']

In [19]:
#let's see our games with a total_sales of 0
df.loc[df.total_sales==0]

,rank,name,genre,esrb_rating,platform,publisher,developer,critic_score,user_score,total_shipped,global_sales,na_sales,pal_sales,jp_sales,other_sales,year,total_sales
19862,19863,Nari Kids Park: Ultraman R/B,Action,NaN,NS,Bandai Namco Games,Bandai Namco Games,NaN,NaN,0.0,0.0,NaN,NaN,0.0,NaN,2018.0,0.0
19863,19864,Nekketsu Inou Bukatsu: Trigger Kiss,Adventure,NaN,PSV,Idea Factory,Idea Factory,NaN,NaN,0.0,0.0,NaN,NaN,0.0,NaN,2014.0,0.0
19864,19865,Rampage Puzzle Attack,Puzzle,E,GBA,Midway Games,Ninai Games,NaN,NaN,0.0,0.0,0.0,0.0,NaN,0.0,2001.0,0.0
19865,19866,Duke Nukem Trilogy: Critical Mass,Shooter,T,PSP,Unknown,FrontLine Studios,NaN,NaN,0.0,0.0,0.0,NaN,NaN,0.0,2001.0,0.0
19866,19867,The World of Golden Eggs: Nori Nori Uta Dekich...,Puzzle,NaN,DS,AQ Interactive,AQ Interactive,NaN,NaN,0.0,0.0,NaN,NaN,0.0,NaN,2009.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55787,55788,Indivisible,Role-Playing,NaN,PC,505 Games,Lab Zero Games,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,2019.0,0.0
55788,55789,Lost Ember,Adventure,RP,PC,Mooneye Studios,Mooneye Studios,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,2019.0,0.0
55789,55790,Lost Ember,Adventure,RP,PS4,Mooneye Studios,Mooneye Studios,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,2019.0,0.0
55790,55791,Lost Ember,Adventure,RP,XOne,Mooneye Studios,Mooneye Studios,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,2019.0,0.0
55791,55792,Falcon Age,Action-Adventure,NaN,PS4,Unknown,Outerloop Games,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0

Since I've never heard of these games before, I won't drop them just yet. Maybe there's something in common with them that causes their sales to be 0.